# start from nodejs image
FROM node:15.10.0-alpine3.11

# set working directory
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json .

# nodejs
RUN yarn install

# copy rest of web to app
COPY . .

CMD ["yarn", "run", "start"]
