# start from nodejs image
FROM node:15.10.0-alpine3.11

# set working directory
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

#React on port 3000
EXPOSE 3000

# copy package.json to install dependencies
COPY package.json .

# nodejs
RUN npm install

# copy rest of web to app
COPY . .

#Run development
CMD ["npm", "run", "dev"]
