version: "3.9"

#defining services
services:
  db: # database POSTGRES service
    image: postgres
    environment:
      - POSTGRES_DB=db_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    command:
      -p 5432 # listen on port 5432, default port either way
    volumes:
       - ./temp/data/pgsql:/var/lib/postgresql/data
    restart: always

  rest_api:
    build:
      context: ./app/rest_api/
      dockerfile: Dockerfile.dev

    volumes:
      - ./app/rest_api/:/app/

    ports:
      - "8000:8000"

    env_file:
      - ./.env.dev

    depends_on:
      - db

  frontend:
    stdin_open: true

    build:
      context: ./app/frontend/
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - /app/node_modules/
      - ./app/frontend/:/app/
    environment:
      - CHOKIDAR_USEPOLLING=true
