version: "3.9"

#defining services
services:
  db: # database POSTGRES service
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command:
      -p 5432 # listen on port 5432, default port either way
    #volumes:
       #- ./temp/data/pgsql:/var/lib/postgresql/data
  web:
    build: .
    command: python init_setup.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
