version: "3.9"

#defining services
services:
  db: # database POSTGRES service
    image: postgres
    environment:
      - POSTGRES_DB=db_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    command:
      -p 5432 # listen on port 5432, default port either way
    volumes:
       - ./temp/data/pgsql:/var/lib/postgresql/data
    restart: always

  rest_api:
    build: ./app/rest_api/
    command: python init_setup.py
    volumes:
      - ./app/rest_api/:/app/rest_api/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  frontend:
    build: ./app/frontend/
    command: yarn start
    volumes:
      - ./app/frontend/:/app/frontend/
    ports:
      - "3000:3000"
      - "35729:35729"
    env_file:
      - ./.env.dev
    stdin_open: true
    depends_on:
      - rest_api
