# start from python alpine image
FROM python:3.10.0a7-buster

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y gcc netcat-openbsd && \
    apt-get clean

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

WORKDIR /usr/src/app

COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY . /usr/src/app
ENTRYPOINT ["/usr/src/app/entrypoint.sh","python","init_setup.py"]
