# Generated by Django 3.1.7 on 2021-03-15 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas_core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseidea',
            options={'ordering': ['last_modified']},
        ),
        migrations.AddField(
            model_name='baseidea',
            name='title',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='baseidea',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
